name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    container:
      image: horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake ..
        make -j
        cd ..
        # remove the SocialRobot installation in the docker image as it's not up-to-date
        rm -rf /opt/local/SocialRobot
        pip3 install -e .
    - name: Static python syntax checking
      run: |
        pip3 install flake8
        # static python syntax checking
        flake8 ./python --count --select=E9,F63,F7,F82 --show-source --statistics
        # report warnings, ignore E501 line too long
        flake8 ./python --count --exit-zero --max-complexity=12 --ignore=E501 --statistics
    - name: Check code style
      run: |
        pre-commit install
        clang-format --version
        if ! pre-commit run -a ; then
          git diff
          exit 1
        fi
    - name: Test with pytest
      run: |
        cd ./python/social_bot/envs
        # not clear why social_bot cannot be found. So we have to add it to PYTHONPATH
        PYTHONPATH="$(pwd)/../..:/usr/lib/python3.7/site-packages:$PYTHONPATH" GAZEBO_MODEL_PATH=../models xvfb-run python3 -m unittest discover -p "*_test.py" -v
